// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gzunvwllnrykwaqtiqhj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd6dW52d2xsbnJ5a3dhcXRpcWhqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIxMTYwNjQsImV4cCI6MjA4NzY5MjA2NH0.v6osjGZ__UAQjnoiBqj-xgPw-fNEaSIjcVkqhn2x9Eo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});