// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://krifrswzuzvyejrndjey.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtyaWZyc3d6dXp2eWVqcm5kamV5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIxMDc3MjAsImV4cCI6MjA4NzY4MzcyMH0.s1NmUcWPpAAHPy1_qCCg78C1xT0U--IzhiemsbT71ps";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});